spring: 
  profiles: 
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name:microservicecloud-config-ryuan-dev
---
spring:
  profiles: test
  application:
    name:microservicecloud-config-ryuan-test